[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    pololu/VL53L0X
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson
    madhephaestus/ESP32Encoder
    links2004/WebSockets

[env:producao]
build_src_filter = +<*> -<scripts_teste/>

[env:teste_encoders]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_encoders.cpp>

[env:teste_motores]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_motores.cpp>

[env:teste_imu]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_imu.cpp>

[env:teste_tof]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_tof.cpp>

[env:teste_reta_imu]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_reta_imu.cpp>

[env:teste_giro_imu]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_giro_imu.cpp>

[env:teste_conexao]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_conexao.cpp>

[env:teste_giro_stress]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_giro_stress.cpp>

[env:teste_encoders_wifi]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_encoders_wifi.cpp>

[env:teste_tof_wifi]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_tof_wifi.cpp>

[env:teste_ws]
build_src_filter = +<*> -<main.cpp> -<scripts_teste/> +<scripts_teste/teste_ws.cpp>

